DROP TABLE IF EXISTS countries;
DROP TABLE IF EXISTS cities;
DROP TABLE IF EXISTS streets;
DROP TABLE IF EXISTS streets_numbers;
DROP TABLE IF EXISTS staircases;
DROP TABLE IF EXISTS floors;
DROP TABLE IF EXISTS doors;
DROP TABLE IF EXISTS zip_codes;



CREATE TABLE countries (
id_country INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
country VARCHAR(64)
);

CREATE TABLE cities(
id_city INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
city VARCHAR(64),
id_country INT UNSIGNED,
FOREIGN KEY (id_country) REFERENCES countries(id_country)
);

CREATE TABLE streets(
id_street INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
street VARCHAR(64),
id_city INT UNSIGNED,
FOREIGN KEY (id_city) REFERENCES cities(id_city)
);

CREATE TABLE streets_numbers(
id_street_number INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
street_number VARCHAR(32)
);

CREATE TABLE staircases(
id_staircase INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
staircase VARCHAR(32)
);

CREATE TABLE floors(
id_floor INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
`floor` VARCHAR(32)
);

CREATE TABLE doors(
id_door INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
door VARCHAR(32)
);

CREATE TABLE zip_codes(
id_zip_code INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
zip_code VARCHAR(32)
);






